//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use super::sea_orm_active_enums::PostTypeEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "posts")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub r#type: PostTypeEnum,
    pub author_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    pub spot_id: Option<Uuid>,
    pub original_post_id: Option<Uuid>,
    pub like_count: i32,
    pub comment_count: i32,
    pub repost_count: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::post_bookmarks::Entity")]
    PostBookmarks,
    #[sea_orm(has_many = "super::post_likes::Entity")]
    PostLikes,
    #[sea_orm(has_many = "super::post_photos::Entity")]
    PostPhotos,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::OriginalPostId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::spots::Entity",
        from = "Column::SpotId",
        to = "super::spots::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Spots,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::AuthorId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::post_bookmarks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostBookmarks.def()
    }
}

impl Related<super::post_likes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostLikes.def()
    }
}

impl Related<super::post_photos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostPhotos.def()
    }
}

impl Related<super::spots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Spots.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
