//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::user_auth_providers::Entity as UserAuthProviders;
pub use super::users::Entity as Users;
