//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "auth_provider_type")]
pub enum AuthProviderType {
    #[sea_orm(string_value = "email")]
    Email,
    #[sea_orm(string_value = "google")]
    Google,
    #[sea_orm(string_value = "facebook")]
    Facebook,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "gender_type")]
pub enum GenderType {
    #[sea_orm(string_value = "male")]
    Male,
    #[sea_orm(string_value = "female")]
    Female,
    #[sea_orm(string_value = "prefer_not_to_say")]
    PreferNotToSay,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "post_type_enum")]
pub enum PostTypeEnum {
    #[sea_orm(string_value = "standard")]
    Standard,
    #[sea_orm(string_value = "comment")]
    Comment,
    #[sea_orm(string_value = "repost")]
    Repost,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "user_badge_type_enum"
)]
pub enum UserBadgeTypeEnum {
    #[sea_orm(string_value = "local_legend")]
    LocalLegend,
    #[sea_orm(string_value = "explorer")]
    Explorer,
    #[sea_orm(string_value = "contributor")]
    Contributor,
}
