//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::{entity::prelude::*, IntoActiveValue};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "auth_provider_type")]
pub enum AuthProviderType {
    #[sea_orm(string_value = "email")]
    Email,
    #[sea_orm(string_value = "google")]
    Google,
    #[sea_orm(string_value = "facebook")]
    Facebook,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "gender_type")]
pub enum GenderType {
    #[sea_orm(string_value = "male")]
    Male,
    #[sea_orm(string_value = "female")]
    Female,
    #[sea_orm(string_value = "prefer_not_to_say")]
    PreferNotToSay,
}

/// Convert `GenderType` to `ActiveValue`
impl IntoActiveValue<GenderType> for GenderType {
    fn into_active_value(self) -> sea_orm::ActiveValue<GenderType> {
        sea_orm::ActiveValue::Set(self)
    }
}

/// Convert `AuthProviderType` to `ActiveValue`
impl IntoActiveValue<AuthProviderType> for AuthProviderType {
    fn into_active_value(self) -> sea_orm::ActiveValue<AuthProviderType> {
        sea_orm::ActiveValue::Set(self)
    }
}
