//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "spots")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Decimal(Some((2, 1)))")]
    pub rating: Decimal,
    #[sea_orm(column_type = "Text")]
    pub location: String,
    #[sea_orm(column_type = "Double")]
    pub latitude: f64,
    #[sea_orm(column_type = "Double")]
    pub longitude: f64,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub photo_urls: Vec<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub attributes: Json,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub phone: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub website: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::posts::Entity")]
    Posts,
    #[sea_orm(has_many = "super::seasonal_pickings::Entity")]
    SeasonalPickings,
    #[sea_orm(has_many = "super::spot_label_assignments::Entity")]
    SpotLabelAssignments,
    #[sea_orm(has_many = "super::spot_opening_hours::Entity")]
    SpotOpeningHours,
    #[sea_orm(has_one = "super::tips::Entity")]
    Tips,
    #[sea_orm(has_many = "super::user_saved_spots::Entity")]
    UserSavedSpots,
}

impl Related<super::posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Posts.def()
    }
}

impl Related<super::seasonal_pickings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeasonalPickings.def()
    }
}

impl Related<super::spot_label_assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpotLabelAssignments.def()
    }
}

impl Related<super::spot_opening_hours::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpotOpeningHours.def()
    }
}

impl Related<super::tips::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tips.def()
    }
}

impl Related<super::user_saved_spots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSavedSpots.def()
    }
}

impl Related<super::spot_labels::Entity> for Entity {
    fn to() -> RelationDef {
        super::spot_label_assignments::Relation::SpotLabels.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::spot_label_assignments::Relation::Spots.def().rev())
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_saved_spots::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_saved_spots::Relation::Spots.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
