//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "spot_label_assignments")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub spot_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub label_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::spot_labels::Entity",
        from = "Column::LabelId",
        to = "super::spot_labels::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SpotLabels,
    #[sea_orm(
        belongs_to = "super::spots::Entity",
        from = "Column::SpotId",
        to = "super::spots::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Spots,
}

impl Related<super::spot_labels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpotLabels.def()
    }
}

impl Related<super::spots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Spots.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
