//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "spot_labels")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text")]
    pub icon: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::spot_label_assignments::Entity")]
    SpotLabelAssignments,
}

impl Related<super::spot_label_assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpotLabelAssignments.def()
    }
}

impl Related<super::spots::Entity> for Entity {
    fn to() -> RelationDef {
        super::spot_label_assignments::Relation::Spots.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::spot_label_assignments::Relation::SpotLabels
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
