//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "tips")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub author_id: Uuid,
    #[sea_orm(unique)]
    pub spot_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    pub helpful_count: i32,
    pub is_top_tip: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::spots::Entity",
        from = "Column::SpotId",
        to = "super::spots::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Spots,
    #[sea_orm(has_many = "super::tip_votes::Entity")]
    TipVotes,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::AuthorId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::spots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Spots.def()
    }
}

impl Related<super::tip_votes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TipVotes.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::tip_votes::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::tip_votes::Relation::Tips.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
