[package]
name = "explonz_shared"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = "0.28.0"
strum_macros = "0.28.0"
sea-orm      = { workspace = true, optional = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
validator    = { workspace = true }
uuid         = { workspace = true }
chrono       = { workspace = true }
rust_decimal = { workspace = true }
bcrypt = { workspace = true, optional = true }
anyhow = { workspace = true, optional = true }
jsonwebtoken = { workspace = true, optional = true }
sha2         = { workspace = true, optional = true }
hex          = { workspace = true, optional = true }
xid          = { workspace = true, optional = true }  



[features]
ssr = [
    "dep:sea-orm",
    "dep:bcrypt",
    "dep:anyhow",
    "dep:jsonwebtoken",  # 新增
    "dep:sha2",          # 新增
    "dep:hex",           # 新增
    "dep:xid",           # 新增
]