server:
  host: "192.168.68.50"
  # host: "192.168.183.80"
  port: 3005

database:
  host: "127.0.0.1"
  port: 5432
  user: "wangweichun"
  password: "WW_33_cc"
  db_name: "explonz_app"
  schema: "public"

#database pool settings:
pool:
  min_connections: 10
  max_connections: 20
  connect_timeout: 10 # seconds
  read_timeout: 20 # seconds
  idle_timeout: 300 # seconds
  max_lifetime: 24 # hours

email:
  sender: "onboarding@resend.dev"
  password: "WW_33_cc163!"
  api_key: "" # 待办：存入到 .env 环境变量中
  attempts: "5"  # otp code 最多可以尝试的次数
  otp_code_validity_time: "2"  # otp code 的有效时间（分钟）

# 管理员后台账号
# admin:
#   account: ${ADMIN_ACCOUNT}
#   password: ${ADMIN_PASSWORD_HASH}
  