//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::post_bookmarks::Entity as PostBookmarks;
pub use super::post_likes::Entity as PostLikes;
pub use super::post_photos::Entity as PostPhotos;
pub use super::posts::Entity as Posts;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::seasonal_pickings::Entity as SeasonalPickings;
pub use super::sign_up_otps::Entity as SignUpOtps;
pub use super::spot_opening_hours::Entity as SpotOpeningHours;
pub use super::spots::Entity as Spots;
pub use super::tip_votes::Entity as TipVotes;
pub use super::tips::Entity as Tips;
pub use super::user_auth_providers::Entity as UserAuthProviders;
pub use super::user_saved_spots::Entity as UserSavedSpots;
pub use super::users::Entity as Users;
