//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "seasonal_pickings")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub spot_id: Uuid,
    pub season_start_month: i16,
    pub season_start_day: i16,
    pub season_end_month: i16,
    pub season_end_day: i16,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::spots::Entity",
        from = "Column::SpotId",
        to = "super::spots::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Spots,
}

impl Related<super::spots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Spots.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
