//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "spot_opening_hours")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub spot_id: Uuid,
    pub day_of_week: i16,
    pub is_closed: bool,
    pub is_open_24h: bool,
    pub open_time: Option<Time>,
    pub close_time: Option<Time>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::spots::Entity",
        from = "Column::SpotId",
        to = "super::spots::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Spots,
}

impl Related<super::spots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Spots.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
