//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use super::sea_orm_active_enums::GenderType;
use super::sea_orm_active_enums::UserBadgeTypeEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "users")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub nickname: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub email: Option<String>,
    pub gender: Option<GenderType>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub badge_type: Option<UserBadgeTypeEnum>,
    #[sea_orm(column_type = "Text", nullable)]
    pub badge_label: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::post_bookmarks::Entity")]
    PostBookmarks,
    #[sea_orm(has_many = "super::post_likes::Entity")]
    PostLikes,
    #[sea_orm(has_many = "super::posts::Entity")]
    Posts,
    #[sea_orm(has_many = "super::refresh_tokens::Entity")]
    RefreshTokens,
    #[sea_orm(has_many = "super::tip_votes::Entity")]
    TipVotes,
    #[sea_orm(has_many = "super::tips::Entity")]
    Tips,
    #[sea_orm(has_many = "super::user_auth_providers::Entity")]
    UserAuthProviders,
    #[sea_orm(has_many = "super::user_saved_spots::Entity")]
    UserSavedSpots,
}

impl Related<super::post_bookmarks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostBookmarks.def()
    }
}

impl Related<super::post_likes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostLikes.def()
    }
}

impl Related<super::posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Posts.def()
    }
}

impl Related<super::refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokens.def()
    }
}

impl Related<super::tip_votes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TipVotes.def()
    }
}

impl Related<super::user_auth_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAuthProviders.def()
    }
}

impl Related<super::user_saved_spots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSavedSpots.def()
    }
}

impl Related<super::spots::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_saved_spots::Relation::Spots.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_saved_spots::Relation::Users.def().rev())
    }
}

impl Related<super::tips::Entity> for Entity {
    fn to() -> RelationDef {
        super::tip_votes::Relation::Tips.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::tip_votes::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
